import 'package:flutter/material.dart';

void main() => runApp(const PairPlayApp());

enum AppLang { bn, en, hi }

class L10n {
  static AppLang lang = AppLang.en;
  static const data = <String, Map<AppLang, String>>{
    'app': {AppLang.en:'PairPlay', AppLang.bn:'পেয়ারপ্লে', AppLang.hi:'पेयरप्ले'},
    'home': {AppLang.en:'Home', AppLang.bn:'হোম', AppLang.hi:'होम'},
    'discover': {AppLang.en:'Discover', AppLang.bn:'ডিসকভার', AppLang.hi:'डिस्कवर'},
    'games': {AppLang.en:'Games', AppLang.bn:'গেম', AppLang.hi:'गेम्स'},
    'couple': {AppLang.en:'Couple Room', AppLang.bn:'কাপল রুম', AppLang.hi:'कपल रूम'},
    'profile': {AppLang.en:'Profile', AppLang.bn:'প্রোফাইল', AppLang.hi:'प्रोफ़ाइल'},
    'play': {AppLang.en:'Play first. Match naturally. Talk privately.', AppLang.bn:'আগে খেলো। স্বাভাবিকভাবে ম্যাচ হও। তারপর ব্যক্তিগতভাবে কথা বলো।', AppLang.hi:'पहले खेलो। स्वाभाविक मैच करो। फिर निजी तौर पर बात करो।'},
    'find': {AppLang.en:'Find Your Match', AppLang.bn:'তোমার ম্যাচ খুঁজো', AppLang.hi:'अपना मैच खोजें'},
    'daily': {AppLang.en:'Question of the Day', AppLang.bn:'আজকের প্রশ্ন', AppLang.hi:'आज का सवाल'},
    'private': {AppLang.en:'Private by design', AppLang.bn:'শুরু থেকেই প্রাইভেট', AppLang.hi:'शुरू से ही निजी'},
    'no_group': {AppLang.en:'No group chat • No anonymous chat • One active partner', AppLang.bn:'কোনো গ্রুপ চ্যাট নয় • কোনো anonymous chat নয় • এক সময়ে একজন পার্টনার', AppLang.hi:'कोई ग्रुप चैट नहीं • कोई anonymous chat नहीं • एक समय में एक पार्टनर'},
    'language': {AppLang.en:'Language', AppLang.bn:'ভাষা', AppLang.hi:'भाषा'},
  };
  static String t(String key) => data[key]?[lang] ?? data[key]?[AppLang.en] ?? key;
}

PreferredSizeWidget pairAppBar(BuildContext context, String title) => AppBar(leading: Navigator.of(context).canPop() ? IconButton(icon: const Icon(Icons.arrow_back_rounded), onPressed: () => Navigator.of(context).pop()) : null, title: Text(title, style: const TextStyle(fontWeight: FontWeight.w800)));

class Question {
  final String id;
  final Map<AppLang, String> text;
  final List<Map<AppLang, String>> options;
  const Question(this.id, this.text, this.options);
}

const questions = <Question>[
  Question('date-01', {AppLang.en:'Your perfect first date?',AppLang.bn:'প্রথম ডেট তোমার কাছে কেমন হওয়া উচিত?',AppLang.hi:'आपकी परफेक्ट पहली डेट कैसी होगी?'}, [
    {AppLang.en:'Coffee',AppLang.bn:'কফি',AppLang.hi:'कॉफी'}, {AppLang.en:'Beach',AppLang.bn:'বিচ',AppLang.hi:'बीच'}, {AppLang.en:'Movie',AppLang.bn:'মুভি',AppLang.hi:'मूवी'}, {AppLang.en:'Dinner',AppLang.bn:'ডিনার',AppLang.hi:'डिनर'}]),
  Question('weekend-01', {AppLang.en:'Ideal weekend?',AppLang.bn:'আদর্শ উইকেন্ড?',AppLang.hi:'आदर्श वीकेंड?'}, [
    {AppLang.en:'Stay in',AppLang.bn:'বাসায় থাকা',AppLang.hi:'घर पर रहना'}, {AppLang.en:'Travel',AppLang.bn:'ঘুরতে যাওয়া',AppLang.hi:'घूमना'}, {AppLang.en:'Friends',AppLang.bn:'বন্ধুদের সাথে',AppLang.hi:'दोस्तों के साथ'}, {AppLang.en:'Family',AppLang.bn:'পরিবারের সাথে',AppLang.hi:'परिवार के साथ'}]),
  Question('morning-01', {AppLang.en:'Morning or late night?',AppLang.bn:'সকাল নাকি গভীর রাত?',AppLang.hi:'सुबह या देर रात?'}, [
    {AppLang.en:'Morning',AppLang.bn:'সকাল',AppLang.hi:'सुबह'}, {AppLang.en:'Late night',AppLang.bn:'গভীর রাত',AppLang.hi:'देर रात'}, {AppLang.en:'Both',AppLang.bn:'দুটোই',AppLang.hi:'दोनों'}, {AppLang.en:'Depends',AppLang.bn:'পরিস্থিতি অনুযায়ী',AppLang.hi:'परिस्थिति पर निर्भर'}]),
  Question('travel-01', {AppLang.en:'Pick one escape.',AppLang.bn:'একটা জায়গা বেছে নাও।',AppLang.hi:'एक जगह चुनें।'}, [
    {AppLang.en:'Mountain',AppLang.bn:'পাহাড়',AppLang.hi:'पहाड़'}, {AppLang.en:'Sea',AppLang.bn:'সমুদ্র',AppLang.hi:'समुद्र'}, {AppLang.en:'City',AppLang.bn:'শহর',AppLang.hi:'शहर'}, {AppLang.en:'Village',AppLang.bn:'গ্রাম',AppLang.hi:'गाँव'}]),
  Question('food-01', {AppLang.en:'Comfort food?',AppLang.bn:'Comfort food কোনটা?',AppLang.hi:'Comfort food क्या है?'}, [
    {AppLang.en:'Pizza',AppLang.bn:'পিজ্জা',AppLang.hi:'पिज़्ज़ा'}, {AppLang.en:'Biryani',AppLang.bn:'বিরিয়ানি',AppLang.hi:'बिरयानी'}, {AppLang.en:'Burger',AppLang.bn:'বার্গার',AppLang.hi:'बर्गर'}, {AppLang.en:'Noodles',AppLang.bn:'নুডলস',AppLang.hi:'नूडल्स'}]),
  Question('chat-01', {AppLang.en:'What matters more?',AppLang.bn:'কোনটা বেশি গুরুত্বপূর্ণ?',AppLang.hi:'क्या ज्यादा मायने रखता है?'}, [
    {AppLang.en:'Humor',AppLang.bn:'হাস্যরস',AppLang.hi:'ह्यूमर'}, {AppLang.en:'Trust',AppLang.bn:'বিশ্বাস',AppLang.hi:'भरोसा'}, {AppLang.en:'Communication',AppLang.bn:'যোগাযোগ',AppLang.hi:'बातचीत'}, {AppLang.en:'Adventure',AppLang.bn:'অ্যাডভেঞ্চার',AppLang.hi:'एडवेंचर'}]),
];

class PairPlayApp extends StatefulWidget {
  const PairPlayApp({super.key});
  @override State<PairPlayApp> createState() => _PairPlayAppState();
}

class _PairPlayAppState extends State<PairPlayApp> {
  AppLang lang = AppLang.en;
  @override Widget build(BuildContext context) {
    L10n.lang = lang;
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'PairPlay',
      theme: ThemeData(useMaterial3:true, fontFamily:'Arial', colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFFEE4F78)), scaffoldBackgroundColor: const Color(0xFFFFF8FA)),
      home: WelcomeScreen(onLanguage: (v){setState(()=>lang=v);}),
    );
  }
}

class WelcomeScreen extends StatelessWidget {
  final ValueChanged<AppLang> onLanguage;
  const WelcomeScreen({super.key, required this.onLanguage});
  @override Widget build(BuildContext context) => Scaffold(body: SafeArea(child: Padding(padding: const EdgeInsets.all(24), child: Column(crossAxisAlignment:CrossAxisAlignment.stretch, children:[
    Align(alignment:Alignment.topRight, child: DropdownButton<AppLang>(value:L10n.lang, onChanged:(v){if(v!=null) onLanguage(v);}, items: const [DropdownMenuItem(value:AppLang.bn,child:Text('বাংলা')),DropdownMenuItem(value:AppLang.en,child:Text('English')),DropdownMenuItem(value:AppLang.hi,child:Text('हिन्दी'))])),
    const Spacer(), Center(child: Container(width:96,height:96,decoration:BoxDecoration(gradient: const LinearGradient(colors:[Color(0xFFFFD4DE),Color(0xFFE3D9FF)]),borderRadius: BorderRadius.all(Radius.circular(30))),child: const Center(child:Text('💞',style:TextStyle(fontSize:48))))),
    const SizedBox(height:22), const Center(child:Text('PairPlay',style:TextStyle(fontSize:42,fontWeight:FontWeight.w900))), const SizedBox(height:10), Center(child:Text(L10n.t('play'),textAlign:TextAlign.center,style:const TextStyle(fontSize:17,color:Color(0xFF756C79),height:1.45))),
    const SizedBox(height:24), _Pill(icon:Icons.sports_esports_rounded,text:'🎮  Compatibility games'), const SizedBox(height:10), _Pill(icon:Icons.lock_rounded,text:'🔐  Private 1-to-1 couple room'), const SizedBox(height:10), _Pill(icon:Icons.translate_rounded,text:'🌍  বাংলা • English • हिन्दी'),
    const Spacer(), SizedBox(height:54,child:FilledButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const AgeGate())),icon:const Icon(Icons.login_rounded),label:const Text('Continue with Google',style:TextStyle(fontWeight:FontWeight.w800,fontSize:16)))), const SizedBox(height:12), Center(child:Text(L10n.t('no_group'),textAlign:TextAlign.center,style:const TextStyle(fontSize:12,color:Color(0xFF756C79)))),
  ])));
}
class _Pill extends StatelessWidget { final IconData icon; final String text; const _Pill({required this.icon,required this.text}); @override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(horizontal:15,vertical:13),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16)),child:Row(children:[Icon(icon,size:19,color:const Color(0xFFEE4F78)),const SizedBox(width:10),Text(text,style:const TextStyle(fontWeight:FontWeight.w700))]));}

class AgeGate extends StatefulWidget { const AgeGate({super.key}); @override State<AgeGate> createState()=>_AgeGateState(); }
class _AgeGateState extends State<AgeGate>{ bool ok=false; @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text('PairPlay',style:const TextStyle(fontWeight:FontWeight.w800))),body:Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const SizedBox(height:18),const Text('18+ only',style:TextStyle(fontSize:34,fontWeight:FontWeight.w900)),const SizedBox(height:10),Text('Matchmaking and private messaging are available only to adults.',style:TextStyle(color:Colors.grey.shade700,fontSize:16,height:1.45)),const SizedBox(height:20),Card(child:Padding(padding:const EdgeInsets.all(18),child:Text('You confirm you are 18 or older and agree to the Terms and Community Guidelines.'))),const SizedBox(height:14),CheckboxListTile(value:ok,onChanged:(v)=>setState(()=>ok=v??false),contentPadding:EdgeInsets.zero,title:const Text('I am 18 or older'),controlAffinity:ListTileControlAffinity.leading),const Spacer(),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:ok?()=>Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const ProfileSetup())):null,child:const Text('Continue'))]))); }

class ProfileSetup extends StatefulWidget{const ProfileSetup({super.key});@override State<ProfileSetup>createState()=>_ProfileSetupState();}
class _ProfileSetupState extends State<ProfileSetup>{final name=TextEditingController();String gender='';final interests=<String>{};@override Widget build(BuildContext c){final can=name.text.trim().length>=2&&gender.isNotEmpty&&interests.isNotEmpty;return Scaffold(appBar:AppBar(title:const Text('Build your profile',style:TextStyle(fontWeight:FontWeight.w800))),body:ListView(padding:const EdgeInsets.all(24),children:[const Text('Let’s get your vibe right.',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Male + Female matching is enforced by the matching rules.',style:TextStyle(color:Color(0xFF756C79))),const SizedBox(height:22),TextField(controller:name,onChanged:(_)=>setState((){}),decoration:const InputDecoration(labelText:'First name')),const SizedBox(height:18),const Text('I am',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:10),Row(children:[Expanded(child:_Gender(label:'Male',selected:gender=='Male',onTap:()=>setState(()=>gender='Male'))),const SizedBox(width:10),Expanded(child:_Gender(label:'Female',selected:gender=='Female',onTap:()=>setState(()=>gender='Female')))]),const SizedBox(height:20),const Text('Interests',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:8),Wrap(spacing:8,runSpacing:8,children:['Travel','Music','Movies','Food','Gaming','Nature','Books','Fitness'].map((x)=>FilterChip(label:Text(x),selected:interests.contains(x),onSelected:(v)=>setState(()=>v?interests.add(x):interests.remove(x))).toList())),const SizedBox(height:26),SizedBox(height:52,child:FilledButton(onPressed:can?()=>Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>Home(name:name.text.trim()))):null,child:const Text('Enter PairPlay',style:TextStyle(fontWeight:FontWeight.w800))))]));}}
class _Gender extends StatelessWidget{final String label;final bool selected;final VoidCallback onTap;const _Gender({required this.label,required this.selected,required this.onTap});@override Widget build(BuildContext c)=>InkWell(onTap:onTap,borderRadius:BorderRadius.circular(17),child:AnimatedContainer(duration:const Duration(milliseconds:180),padding:const EdgeInsets.symmetric(vertical:16),decoration:BoxDecoration(color:selected?const Color(0xFFFFE7ED):Colors.white,borderRadius:BorderRadius.circular(17),border:Border.all(color:selected?const Color(0xFFEE4F78):const Color(0xFFEAE3E7))),child:Center(child:Text(label,style:TextStyle(fontWeight:FontWeight.w800,color:selected?const Color(0xFFEE4F78):const Color(0xFF756C79))))));}

class Home extends StatefulWidget{final String name;const Home({super.key,required this.name});@override State<Home>createState()=>_HomeState();}
class _HomeState extends State<Home>{int tab=0;final seen=<String>{};int gamesPlayed=0;Question get nextQuestion=>questions.firstWhere((q)=>!seen.contains(q.id),orElse:()=>questions[gamesPlayed%questions.length]);@override Widget build(BuildContext c){final pages=[HomeTab(name:widget.name,onPlay:()=>setState(()=>tab=2)),const DiscoverTab(),GameLobby(seen:seen,onPlayed:(){setState(()=>gamesPlayed++);}),const CoupleTab(),const ProfileTab()];return Scaffold(body:SafeArea(child:pages[tab]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:[NavigationDestination(icon:const Icon(Icons.home_outlined),selectedIcon:const Icon(Icons.home),label:L10n.t('home')),NavigationDestination(icon:const Icon(Icons.explore_outlined),selectedIcon:const Icon(Icons.explore),label:L10n.t('discover')),NavigationDestination(icon:const Icon(Icons.sports_esports_outlined),selectedIcon:const Icon(Icons.sports_esports),label:L10n.t('games')),NavigationDestination(icon:const Icon(Icons.favorite_border),selectedIcon:const Icon(Icons.favorite),label:L10n.t('couple')),NavigationDestination(icon:const Icon(Icons.person_outline),selectedIcon:const Icon(Icons.person),label:L10n.t('profile'))]));}}

class HomeTab extends StatelessWidget{final String name;final VoidCallback onPlay;const HomeTab({super.key,required this.name,required this.onPlay});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Good day 👋',style:TextStyle(color:Color(0xFF756C79))),Text(name,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900))])),CircleAvatar(backgroundColor:const Color(0xFFFFE7ED),child:const Icon(Icons.person,color:Color(0xFFEE4F78)))]),const SizedBox(height:20),Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFFEE4F78),Color(0xFF7357F5)]),borderRadius:BorderRadius.circular(26)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Find someone who matches your vibe.',style:TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Play a short game first. Your answers help create a better match.',style:TextStyle(color:Colors.white70)),const SizedBox(height:16),FilledButton.tonal(onPressed:onPlay,child:Text(L10n.t('find'),style:const TextStyle(fontWeight:FontWeight.w800)))])),const SizedBox(height:18),Row(children:[Expanded(child:_Stat('0','Matches')),const SizedBox(width:10),Expanded(child:_Stat('0','Streak')),const SizedBox(width:10),Expanded(child:_Stat('0','Games'))]),const SizedBox(height:20),Card(child:ListTile(leading:const CircleAvatar(backgroundColor:Color(0xFFFFE7ED),child:Text('💭')),title:Text(L10n.t('daily'),style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(L10n.lang==AppLang.bn?'তোমার perfect weekend কেমন?':L10n.lang==AppLang.hi?'आपका परफेक्ट वीकेंड कैसा है?':'What makes a perfect weekend for you?'),trailing:const Icon(Icons.chevron_right))) ]);}
class _Stat extends StatelessWidget{final String n,l;const _Stat(this.n,this.l);@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.symmetric(vertical:15),child:Column(children:[Text(n,style:const TextStyle(fontSize:23,fontWeight:FontWeight.w900)),Text(l,style:const TextStyle(fontSize:12,color:Color(0xFF756C79)))])));}

class DiscoverTab extends StatelessWidget{const DiscoverTab({super.key});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[Text(L10n.t('discover'),style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Discovery happens inside games, not a public people directory.',style:TextStyle(color:Color(0xFF756C79))),const SizedBox(height:18),Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.auto_awesome)),title:const Text('Smart matching',style:TextStyle(fontWeight:FontWeight.w800)),subtitle:const Text('Gender eligibility first, then preferences + game answers + safety signals.')))]);}

class GameLobby extends StatelessWidget{final Set<String> seen;final VoidCallback onPlayed;const GameLobby({super.key,required this.seen,required this.onPlayed});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[const Text('Match Games',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('${seen.length}/${questions.length} core questions explored',style:const TextStyle(color:Color(0xFF756C79))),const SizedBox(height:18),...['This or That','Quick Choice','Emoji Guess','2 Truths 1 Lie','Who Knows Me Better?'].map((g)=>Padding(padding:const EdgeInsets.only(bottom:12),child:Card(child:ListTile(leading:const CircleAvatar(backgroundColor:Color(0xFFFFE7ED),child:Text('🎮')),title:Text(g,style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:const Text('Each round uses a question ID; already-seen questions are skipped.'),trailing:const Icon(Icons.play_circle_fill_rounded,color:Color(0xFFEE4F78)),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>QuestionScreen(seen:seen,onPlayed:onPlayed))))))]);}

class QuestionScreen extends StatefulWidget{final Set<String> seen;final VoidCallback onPlayed;const QuestionScreen({super.key,required this.seen,required this.onPlayed});@override State<QuestionScreen>createState()=>_QuestionScreenState();}
class _QuestionScreenState extends State<QuestionScreen>{String? pick;late Question q;@override void initState(){super.initState();q=questions.firstWhere((x)=>!widget.seen.contains(x.id),orElse:()=>questions[widget.seen.length%questions.length]);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Compatibility round',style:TextStyle(fontWeight:FontWeight.w800))),body:Padding(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(q.text[L10n.lang]??q.text[AppLang.en]!,style:const TextStyle(fontSize:29,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('This question is selected so your previous question history is respected.',style:TextStyle(color:Color(0xFF756C79))),const SizedBox(height:22),...(q.options.map((o){final label=o[L10n.lang]??o[AppLang.en]!;return Padding(padding:const EdgeInsets.only(bottom:11),child:InkWell(onTap:()=>setState(()=>pick=label),borderRadius:BorderRadius.circular(18),child:AnimatedContainer(duration:const Duration(milliseconds:160),padding:const EdgeInsets.all(17),decoration:BoxDecoration(color:pick==label?const Color(0xFFFFE7ED):Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:pick==label?const Color(0xFFEE4F78):const Color(0xFFEAE3E7))),child:Text(label,style:const TextStyle(fontWeight:FontWeight.w700,fontSize:16)))));})),const Spacer(),FilledButton(onPressed:pick==null?null:(){widget.seen.add(q.id);widget.onPlayed();Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const MatchResult()));},child:const Padding(padding:EdgeInsets.symmetric(vertical:14),child:Text('Continue')))]));}
}

class MatchResult extends StatelessWidget{const MatchResult({super.key});@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Text('💞',style:TextStyle(fontSize:74)),const SizedBox(height:14),const Text('Great chemistry!',style:TextStyle(fontSize:35,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Demo engine: production will calculate this from real paired answers.',textAlign:TextAlign.center,style:TextStyle(color:Color(0xFF756C79))),const SizedBox(height:20),const Text('87%',style:TextStyle(fontSize:54,fontWeight:FontWeight.w900,color:Color(0xFFEE4F78))),const Text('Vibe compatibility'),const SizedBox(height:24),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:()=>Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const CoupleTab())),child:const Text('Enter Couple Room')))]))));}

class CoupleTab extends StatelessWidget{const CoupleTab({super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(L10n.t('couple'),style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:12),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(children:[Row(children:[const CircleAvatar(radius:27,child:Text('🌸')),const SizedBox(width:12),const Expanded(child:Text('You & Your Match ❤️',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900))),Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:7),decoration:BoxDecoration(color:const Color(0xFFFFE7ED),borderRadius:BorderRadius.circular(12)),child:const Text('87%'))]),const SizedBox(height:18),Container(height:270,padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:const Color(0xFFFCF9FB),borderRadius:BorderRadius.circular(18)),child:const Column(children:[Align(alignment:Alignment.centerLeft,child:_Bubble('Hey! 👋','them')),Align(alignment:Alignment.centerRight,child:_Bubble('Hi! Nice to meet you ❤️','me')),Align(alignment:Alignment.centerLeft,child:_Bubble('Let’s play another round!','them'))])),const SizedBox(height:12),const TextField(decoration:InputDecoration(hintText:'Write a private message…',suffixIcon:Icon(Icons.send_rounded))),const SizedBox(height:12),Row(children:[OutlinedButton(onPressed:null,child:Text('Report')),const SizedBox(width:8),OutlinedButton(onPressed:null,child:Text('Block')),const Spacer(),OutlinedButton(onPressed:null,child:Text('Unmatch'))])]))]));}
class _Bubble extends StatelessWidget{final String t,type;const _Bubble(this.t,this.type);@override Widget build(BuildContext c)=>Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.symmetric(horizontal:13,vertical:10),decoration:BoxDecoration(color:type=='me'?const Color(0xFFEE4F78):Colors.white,borderRadius:BorderRadius.circular(16)),child:Text(t,style:TextStyle(color:type=='me'?Colors.white:const Color(0xFF1B1720))));}

class ProfileTab extends StatelessWidget{const ProfileTab({super.key});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[const Text('Profile',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:18),Card(child:ListTile(leading:const CircleAvatar(radius:30,child:Text('🧑🏻')),title:const Text('Your profile',style:TextStyle(fontWeight:FontWeight.w900)),subtitle:const Text('Male • 18+'))),const SizedBox(height:14),Card(child:ListTile(leading:const Icon(Icons.translate),title:Text(L10n.t('language')),subtitle:const Text('বাংলা • English • हिन्दी'))),const SizedBox(height:10),Card(child:const ListTile(leading:Icon(Icons.shield_outlined),title:Text('Safety Center'),subtitle:Text('Block, report, unmatch, account controls')))]);}
